-- DESAFIO 1
/*
A EQUIPE DE MARKETING PRECISA DE FAZER UMA PESQUISA SOBRE NOMES MAIS COMUNS DE SEUS CLIENTES
E PRECISA DO NOME E SOBRENOME DE TODOS OS CLIENTES QUE ESTÃO CADASTRADOS NO SISTEMA.

FIRST NAME, LAST NAME
*/

SELECT FirstName, LastName
FROM Person.Person;